apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app-container
        image: us-east1-docker.pkg.dev/stable3j56ju7/codenest/nginx:1.21.5
        ports:
        - containerPort: 80
